version: "3"

services:
  my-app:
    image: nodejs1013
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - .:/my-app
      - /my-app/node_modules
