version: "3"

services:
  my-app:
    image: my-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      # mount current dir into docker container
      - .:/my-app
